### ISSUE TITLE
Gtuner V0.99B crashing/freeze

### ISSUE THREAD

**Issue by stevanos** [J2Kbr/GtunerIV#124] opened 2017-02-28 08:46 UTC
Hi dudes out there,

after a hard weekend of trying to script and configure a git i thought i was finished but now the prblem is that gtuner crashes in capture mode and feeze. 

My setup is

(PC) Logitech G13 Keyboard and Logitech G502 Mouse booth are connected to the PC
(T2) On Port A DS4 orginal PS4 controller
(PS4)
connect PC-T2-PS4

here comes the problem the mouse is setup to 12000dpi when i am in game the mouse movement is not stable it freeze and jumps from point to some where else. So at first i triyed to change the dpi and it was getting better but i can not go down to 1000dpi the mouse movent in game is so slow, that it is not play able even if i adjust it over the sensivity settings. Okay so ill tried to set down the mouse recquest rate same problem but now in the other direction higher get better but gtuner crashes again after a while .
This is not the only problem with the mouse steup i can get Gtuner directly crashing by doing in game my Super this means when  i press ALT+B (for example) at the same time together the result gtunter capture mode freeze and in game i run again the wall and so on. Of course i got the latest Gtuner version and Firmware on the T2

I also deaktivate my firewall and look at the CPU usage.
Gtuner at Capture mode even if it crash the CPU usage stayes at about 13% and 40% of 4GB-RAM are free to use for Gtuner.

[forum thread ](http://www.consoletuner.com/forum/viewtopic.php?f=27&t=5869)

**Comment by J2Kbr** [comment] 2017-03-08 20:42
**Issue 1** - Mouse responsiveness. After few tests it was detected that fast polling mice can overload the Titan Two mouse XY conversion algorithm - this issue is related with the firmware and will be fixed on the next firmware release.

**Issue 2** - Gtuner IV freezing. Tracing this issue down I found the `T1.gph` header is replacing the `set_val` build-in function by `_set_val()`, an variant that outputs the values to Gtuner IV if any TRACE_* designator is used, here is an reproduction of this function:
```
void _set_val(uint8 idx, int32 val)
{
	if ((idx >= TRACE_1) && (idx <= TRACE_6))
	{
		printf("TRACE_%d: %d", idx - (TRACE_1 - 1), val);
	}
	else
	{
		set_val(idx, val);
	}
}

#define set_val(idx, val)		_set_val(idx, val);
```
The issue happens because this code is sending output messages to Gtuner very quickly, potentially more than one per milli-second, what is causing overload of the USB data pipe and Gtuner IV GUI.

To fix this, comment the lines
`set_val (TRACE_4, 100);`
and
`set_val (TRACE_4, 0);`
in your combo _do_super_

Please also check if your code don't have more `set_val (TRACE_*, 0);`.

**Closed as completed by J2Kbr** 2017-03-08 20:42 UTC
