### ISSUE TITLE
Drag & Drop not working for some people after release of GTuner IV ver.2018-12-13, Ver 1.00RC-84

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#284] opened 2018-12-18 19:02 UTC
It looks like some people have issues with drag & drop not working at all after the Release of GTuner IV 2018-12-13, Ver 1.00RC-84 . Not sure if this is the version that introduces the problem or it was happening a version before already.

I could provide an older version "1.0.2.16" for a user for testing purpose and drag & drop is working with this old version for him again:
https://www.consoletuner.com/forum/viewtopic.php?f=27&t=11066&start=30#p76486

Forum Posts:
https://www.consoletuner.com/forum/viewtopic.php?f=27&t=11066&start=20#p76465
https://www.consoletuner.com/forum/viewtopic.php?f=2&t=11155&p=76657#p76656

Also mentioned there: https://github.com/J2Kbr/TitanTwo/issues/180

**Comment by Hyphen-x** [comment] 2018-12-20 04:30
@Scachi 

Go to the bottom to see latest outcome/status/progress. I think i found the disconnect/reconnect current cause. And the drag and drop problem for me may tie into this other problem too. so I put my testing info up to help. 

**I received my new T2 replacing the old one and I set it up for testing during its setup.** 

Re: T2 official known issues thread

Post by Hyphen- » Wed Dec 19, 2018 2:22 pm
I have connected the new T2 to the PS4 .. it is sleeping quietly in the corner and no disconnects from the PS4 going past 1 hour...
I am about to connect it to my computer to view it in GT4 newest version first. will update afterwards...

Post by Hyphen- » Wed Dec 19, 2018 2:44 pm
I connected the T2 setup while idling on PS4 to my computer. The newest release of GT4 would not drag and drop into the T2 memory slots on my Windows 10 v.1607. And all items I had put on with an earlier version lost their configure features and the gear icon disappeared. There still is no disconnect/reconnect issues.

Post by Hyphen- » Wed Dec 19, 2018 3:12 pm
While setting my working directory still in the latest GT4 I decide to see what would happen if I unplugged the usb cable on my computer connected to the prog port.

**The disconnection Triggered here:**

When I did unplug the usb cable from my pc with my DS4 in port B on T2 it disconnected from the PS4 showing the cycling notifications and when I plugged it back in it stopped. And I have repeated it and it occurred again when i unplug the T2 from my computer. But it has not reoccurred while it is plugged in to the computer while GT4 is actively connected to T2 and if I do not unplug it.

My next test will be to turn off GT4 then unplug it but I will enjoy this moment for awhile...

I want to test the older version of GT4 too although I have been advised it will not work properly with the new T2 firmware but not officially from @J2Kbr.

I do not want to unplug from the computer now lest i trigger a more permanent problem. It does not cycle at this point but it may start once i unplug. it. :roll:

Set up: micro usb cable that came withT2 PS4/output, long cable in cable kit from port B to DS4 latest new, A long micro usb cable from prog/computer (mine).

Edit: Also I have the T2 connected to a recommended power supply.

Post by Hyphen- » Wed Dec 19, 2018 3:25 pm
**I turned off GT4 (closed it) and pulled the usb cable out on my computer... and it did not disconnect the controller in port B from the PS4. So that was interesting.**

While the T2 was connected to GT4 latest version and I unplug the T2 from the computer while it is connected it caused the Controller disconnect and reconnect problem. I did not leave it on to see if it would start cycling because I don't want to order another one. Okay what does this mean and can i get a vesion of GT4 that I can use in my windows 10 version I froze it there for a lot of reasons.

Post by bonefisher » Wed Dec 19, 2018 3:46 pm
Check in the device configuration tab on bottom right of GtunerIV while it is plugged in look at power source: to see what is giving the power at this time. Right now mine says DC power jack since my T2 is drawing power from that. If yours says prog. port this is why it disconnects at the time you unplug.

Post by Hyphen- » Wed Dec 19, 2018 4:07 pm
**After disconnecting the T2 from the PC with GT4 newest version program closed. And the T2 active and connected to PS4 home page since the last post 35 minutes ago it has not disconnected the controller from the PS4. I am running out of time to test this but that should give some direction.**

My main question is still is there a version of GT4 that will fix the drag and drop problem with my version of Windows 1607 or older versions or do what versions are you compatible with because to rule that out I would have to reconfigure my hard drives to use the latest Windows 10 which isn't that great.Thanks I am still having fun! :whistling:

Post by Hyphen- » Wed Dec 19, 2018 4:17 pm
@J2Kbr Or you can develop a way to run it in compatibility mode for older versions I have seen that before in script programs (Java) becoming incompatible often as windows changes so rapidly... but I will need a work around to use the latest version of GT4 if you have ideas. Thanks again

    bonefisher wrote:
    **Check in the device configuration tab on bottom right of GtunerIV** while it is plugged in look at power source: to see what is giving the power at this time. Right now mine says DC power jack since my T2 is drawing power from that. If yours says prog. port this is why it disconnects at the time you unplug.

Hey @bonefisher, I have it hooked up to the power supply and it does show up that way in GT4 the problem is caused by the pc maybe as an unwanted power source disrupting the input on contact some how. Check my next test.

update:

**I did some updating to my copy of windows**

Windows 10
2018-05 Update for Windows 10 Version 1607 for x64-based Systems (KB4132216)
2018-07 Cumulative Update for Windows 10 Version 1607 for x64-based Systems (KB4346877)
Fixed some framework problems/denials on com ports but wanted to do this before my next test.

**Same setup after update the disconnection/connection problem changed and became a bit more focused**

**I now can cause the problem to happen on demand** 1, by slowly putting in the usb in its slot to make the connection on the pc from the prog port. As soon as the usb makes contact the both green lights go red and the notification pops up. It happens on connecting or disconnecting the usb connector now with GT4 open or closed and
**the drag and drop still does not work and I once again cannot access the gamepacks that are drag and drop.** :roll:

**But the cycling is not looping continuous like it did before**. I have not loaded any scripts and tried to configure them in game yet and I have a feeling that is when problems would happen possibly. I can use the configuration program on the old version of GT4 but when I load the T2 into the newest one the configuration capabilities disappear there is no gear icon. :unsure:

**Comment by Hyphen-x** [comment] 2018-12-20 07:52
Re: T2 offical known issues thread

Post by Hyphen- » Wed Dec 19, 2018 11:26 pm
Current update:

**I used the older version of GT4** that allows me to drag and drop gamepacks into T2 and

**The setup** short cord the came with T2 output/PS4, long cable from kit Port B/DS4, long cable (mine) T2 prog/PC, and power supply.

**Loaded infinite warfare pack** and configured it. The T2 responded well. Everything worked fine in game and **I was able to configure the game pack in real time** using the older version of GT4 and t**here were no disconnect/reconnect issues**. I left everything connected throughout.

So I can say that **at this point the T2 is working normally** _**excep**t_ for **I cannot use the latest version of GT4 the drag and drop does not work yet** at this time.

**Comment by J2Kbr** [comment] 2018-12-20 12:15
Issue fixed with Gtuner IV 1.00RC-86 (released today). The problem was with the Qt framework 5.12.0, which has a bug with drag-and-drop: 

https://forum.qt.io/topic/97649/bug-in-qt-5-12-drag-n-drop

The Qt framework was downgraded to 5.11.3.

**Closed as completed by J2Kbr** 2018-12-20 12:15 UTC
Labels: bug
