### ISSUE TITLE
Gtuner execution

### ISSUE THREAD

**Issue by prototypeGtuner** [J2Kbr/GtunerIV#86] opened 2016-11-19 06:32 UTC
I have a problem with Gtuner IV that was not with Gtuner Pro. If i close and relaunch Gtuner IV, the Titan Two will sometimes not reconnect correctly and i have to unplug/re-plug the PROG cable to reconnect. If i run 2 instances of Gtuner the Titan Two works on console side but both Gtuner instances are frezzed. 

Connect Fail: Error code: 2, Device: TITAN TWO BETA UNIT N1

With Gtuner Pro and the Titan One i use a USB launcher that when i plug the Titan One it run Gtuner Pro and i can plug/unplug the Titan One's PROG cable without issue.

**Comment by prototypeGtuner** [comment] 2016-11-19 20:25
Sometimes if Gtuner IV is opened when i plug the prog cable the prog led goes orange and the device monitor is greyed. I  quit Gtuner and relaunch and it's still orange and with Connect Fail: Error code: 2. I have to quit Gtuner and unplug the cable.

**Comment by Scachi** [comment] 2016-11-21 09:18
I have a similiar problem with GTuner disconnecting the T2 device on startup of GTuner https://github.com/J2Kbr/GtunerIV/issues/83
If I remove the SD-card, my startup disconnect problem is gone.  Does removing the SD card work for you too ?
The chance for my T2 with SD card is higher to work if I first start Gtuner and connect the T2 prog cable after that.

The only thing to solve this issue for me is to format the sd-card and put the scripts back on it again.
After that it will work for a while without any problem, no matter in which order I start GTuner or connect the prog cable then.

**Comment by prototypeGtuner** [comment] 2016-11-21 11:47
Yes i will try by playing without the SD card for some days to see the difference.

**Comment by Scachi** [comment] 2016-11-21 12:59
No need to play without the sd-card.
Remove the sd-card only for testing when the start of gtuner disconnects the T2 again.
You still have to unplug/replug the cable as you have already done.
Do this with and without the sd-card a few times to test what configuration will start better.
For me, without an sd-card it start and the T2 stays connected without any problem.

With all this sd-card mess it still wonder me why this problem only happens when starting gtuner.
The T2 itself still can handle the sd-card contents without a problem for me. And gtuner sometimes only accepts it when I reformat it.

This problem is driving me crazy.

**Comment by prototypeGtuner** [comment] 2016-11-22 08:29
Ok i will do that and report here.

**Comment by J2Kbr** [comment] 2016-12-08 13:45
As discussed with Scachi by PM on the forums, I was able to reproduce the connection error 2 while ago and after some investigation turned out the cause was related to the Titan Two firmware. I've already fixed on FW 0.80B, to be released within the upcoming days.

**Closed as completed by J2Kbr** 2016-12-08 13:45 UTC
Labels: bug
